// <auto-generated />
using System;
using HackathonApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackathonApi.Migrations
{
    [DbContext(typeof(HackathonDbContext))]
    [Migration("20231117195458_UserUpdate")]
    partial class UserUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("HackathonApi.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KrsNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NipNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegonNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeFirstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeSurname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HackathonApi.Entities.Intership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntershipCreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecrutationEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecrutationStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntershipCreatorId");

                    b.ToTable("Interships");
                });

            modelBuilder.Entity("HackathonApi.Entities.Intership", b =>
                {
                    b.HasOne("HackathonApi.Entities.Company", "IntershipCreator")
                        .WithMany()
                        .HasForeignKey("IntershipCreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntershipCreator");
                });
#pragma warning restore 612, 618
        }
    }
}
